import moment from 'moment';
import { dummyRequest, getStandardResponse } from '../../../extras/CommonHelpers';
import axios from 'axios';

export default {
  getCount: (conditions?: unknown) => getStandardResponse<number>(axios.get('/iro/count', { params: conditions })),
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  getAll: (conditions?: { status?: number }) =>
    getStandardResponse<IROrder[]>(
      dummyRequest<IROrder[]>({
        data: [
          {
            _id: '1',
            IROno: '1234',
            IROdate: moment(),
            division: {
              details: {
                name: '',
                divisionId: '233',
                contactNumber: '89000333',
                email: 'division@gmail.com',
                address: {
                  buildingName: '',
                  street: '',
                  city: '',
                  state: '',
                  country: '',
                  pincode: '',
                },
                noofWorkers: 5,
                noOfSubdivisions: 5,
                noOfChurches: 5,
                coordinator: {
                  _id: '646703c19e433f67d27019b2',
                  basicDetails: {
                    aadhaar: {
                      aadhaarNo: '123456789012',
                    },
                    voterId: {
                      voterIdNo: 'V12345678',
                    },
                    firstName: 'John',
                    lastName: 'Doe',
                    dateOfBirth: moment('2022-12-31T18:30:00.000Z'),
                    gender: 'Male',
                    field: 'Missionary',
                    martialStatus: 'Married',
                    highestQualification: 'Ph.D.',
                    motherTounge: 'English',
                    communicationLanguage: 'English',
                    knownLanguages: ['English', 'Malayalam - മലയാളം'],
                    email: 'abcd@gmail.com',
                    phone: '1234567890',
                    alternativePhone: '9876543210',
                    PANNo: 'ABCD1234',
                    licenseNumber: 'L12345678',
                    permanentAddress: {
                      buildingName: 'Puliyulla parambath',
                      street: '123 Main Street',
                      city: 'Example City',
                      state: 'Example State',
                      country: 'India',
                      pincode: '12345',
                    },
                    currentAddress: {
                      buildingName: 'Puliyulla parambath',
                      street: '456 Elm Street',
                      city: 'Current City',
                      state: 'Current State',
                      country: 'India',
                      pincode: '54321',
                    },
                  },
                  officialDetails: {
                    dateOfJoining: moment('2022-12-31T18:30:00.000Z'),
                    remarks: 'Lorem ipsum dolor sit amet.',
                    selfSupport: true,
                    status: 'Ministering',
                    dateOfDivisionJoining: moment('2023-05-19T04:32:00.077Z'),
                    noOfChurches: 5,
                    subdivision: {
                      _id: 'skjdfj',
                      name: 'ksdfj',
                    },
                  },
                  supportDetails: {
                    totalNoOfYearsInMinistry: 10,
                    withChurch: true,
                  },
                  supportStructure: {
                    basic: 5000,
                    HRA: 2000,
                    spouseAllowance: 1000,
                    positionalAllowance: 500,
                    specialAllowance: 800,
                    impactDeduction: 200,
                    telAllowance: 400,
                    PIONMissionaryFund: 300,
                    MUTDeduction: 100,
                  },
                  createdAt: moment('2023-05-19T05:06:09.292Z'),
                  updatedAt: moment('2023-05-19T05:06:09.292Z'),
                },
                seniorLeader: {
                  _id: '646703c19e433f67d27019b2',

                  basicDetails: {
                    aadhaar: {
                      aadhaarNo: '123456789012',
                    },
                    voterId: {
                      voterIdNo: 'V12345678',
                    },
                    firstName: 'John',
                    lastName: 'Doe',
                    dateOfBirth: moment('2022-12-31T18:30:00.000Z'),
                    gender: 'Male',
                    field: 'Missionary',
                    martialStatus: 'Married',
                    highestQualification: 'Ph.D.',
                    motherTounge: 'English',
                    communicationLanguage: 'English',
                    knownLanguages: ['English', 'Malayalam - മലയാളം'],
                    email: 'abcd@gmail.com',
                    phone: '1234567890',
                    alternativePhone: '9876543210',
                    PANNo: 'ABCD1234',
                    licenseNumber: 'L12345678',
                    permanentAddress: {
                      buildingName: 'Puliyulla parambath',
                      street: '123 Main Street',
                      city: 'Example City',
                      state: 'Example State',
                      country: 'India',
                      pincode: '12345',
                    },
                    currentAddress: {
                      buildingName: 'Puliyulla parambath',
                      street: '456 Elm Street',
                      city: 'Current City',
                      state: 'Current State',
                      country: 'India',
                      pincode: '54321',
                    },
                  },
                  officialDetails: {
                    dateOfJoining: moment('2022-12-31T18:30:00.000Z'),
                    remarks: 'Lorem ipsum dolor sit amet.',
                    selfSupport: true,
                    status: 'Ministering',
                    dateOfDivisionJoining: moment('2023-05-19T04:32:00.077Z'),
                    noOfChurches: 5,
                    subdivision: {
                      _id: 'skjdfj',
                      name: 'ksdfj',
                    },
                  },
                  supportDetails: {
                    totalNoOfYearsInMinistry: 10,
                    withChurch: true,
                  },
                  supportStructure: {
                    basic: 5000,
                    HRA: 2000,
                    spouseAllowance: 1000,
                    positionalAllowance: 500,
                    specialAllowance: 800,
                    impactDeduction: 200,
                    telAllowance: 400,
                    PIONMissionaryFund: 300,
                    MUTDeduction: 100,
                  },
                  createdAt: moment('2023-05-19T05:06:09.292Z'),
                  updatedAt: moment('2023-05-19T05:06:09.292Z'),
                },
                juniorLeader: {
                  _id: '646703c19e433f67d27019b2',

                  basicDetails: {
                    aadhaar: {
                      aadhaarNo: '123456789012',
                    },
                    voterId: {
                      voterIdNo: 'V12345678',
                    },
                    firstName: 'John',
                    lastName: 'Doe',
                    dateOfBirth: moment('2022-12-31T18:30:00.000Z'),
                    gender: 'Male',
                    field: 'Missionary',
                    martialStatus: 'Married',
                    highestQualification: 'Ph.D.',
                    motherTounge: 'English',
                    communicationLanguage: 'English',
                    knownLanguages: ['English', 'Malayalam - മലയാളം'],
                    email: 'abcd@gmail.com',
                    phone: '1234567890',
                    alternativePhone: '9876543210',
                    PANNo: 'ABCD1234',
                    licenseNumber: 'L12345678',
                    permanentAddress: {
                      buildingName: 'Puliyulla parambath',
                      street: '123 Main Street',
                      city: 'Example City',
                      state: 'Example State',
                      country: 'India',
                      pincode: '12345',
                    },
                    currentAddress: {
                      buildingName: 'Puliyulla parambath',
                      street: '456 Elm Street',
                      city: 'Current City',
                      state: 'Current State',
                      country: 'India',
                      pincode: '54321',
                    },
                  },
                  officialDetails: {
                    dateOfJoining: moment('2022-12-31T18:30:00.000Z'),
                    remarks: 'Lorem ipsum dolor sit amet.',
                    selfSupport: true,
                    status: 'Ministering',
                    dateOfDivisionJoining: moment('2023-05-19T04:32:00.077Z'),
                    noOfChurches: 5,
                    subdivision: {
                      _id: 'skjdfj',
                      name: 'ksdfj',
                    },
                  },
                  supportDetails: {
                    totalNoOfYearsInMinistry: 10,
                    withChurch: true,
                  },
                  supportStructure: {
                    basic: 5000,
                    HRA: 2000,
                    spouseAllowance: 1000,
                    positionalAllowance: 500,
                    specialAllowance: 800,
                    impactDeduction: 200,
                    telAllowance: 400,
                    PIONMissionaryFund: 300,
                    MUTDeduction: 100,
                  },
                  createdAt: moment('2023-05-19T05:06:09.292Z'),
                  updatedAt: moment('2023-05-19T05:06:09.292Z'),
                },
              },
              subDivisions: [],
              localBankDetails: {
                accountNumber: 'ksdfjdskfj',
                bankName: 'ksdfjdskfj',
                branchName: 'ksdfjdskfj',
                IFSCCode: 'ksdfjdskfj',
                beneficiary: 'ksdfjdskfj',
              },
              FCRABankDetails: {
                accountNumber: 'ksdfjdskfj',
                bankName: 'ksdfjdskfj',
                branchName: 'ksdfjdskfj',
                IFSCCode: 'ksdfjdskfj',
                beneficiary: 'ksdfjdskfj',
              },
            },
            subDivision: {
              _id: '1',
              name: 'subdivision 1',
            },
            mainCategory: 'Fr request',
            sanction: '50000',
            requestAmount: 0,
            lastUpdateDate: moment(),
            releaseAmount: 0,
            transferredAmount: 0,
            transferredDate: moment(),
            transferredBank: {
              bankName: 'Canara',
              branchName: 'Thodupuzha',
              accountNumber: '4567799',
              IFSCCode: '222',
              beneficiary: '22',
            },
            modeOfPayment: '',
            transactionNumber: '',
          },
        ],
        // error: null,
        message: 'fetched data',
        result: 'success',
        timeout: 500,
      }),
    ),
  // eslint-disable-next-line @typescript-eslint/naming-convention
  saveRelease: (IROrelease: Partial<IROrder>) =>
    getStandardResponse<number>(
      dummyRequest({
        data: IROrelease,
        // error: null,
        message: 'Network Error',
        result: 'success',
        timeout: 500,
      }),
    ),
};
