import moment from 'moment';
import { dummyRequest, getStandardResponse } from '../../../extras/CommonHelpers';
import axios from 'axios';

export default {
  getCount: () => getStandardResponse<number>(
    axios.get('/iro/count'),
  ),
  getAll: () => getStandardResponse<IROrder[]>(
    dummyRequest<IROrder[]>({
      data: [{
        _id: '1',
        IROno: '1234',
        IROdate: moment(),
        division: {
          divisionName: 'Division 1',
          _id: '1',
          divisionId: '233',
          contactNumber: '89000333',
          email: 'division@gmail.com',
          address: {
            buildingName: '',
            street: '',
            city: '',
            district: '',
            state: '',
            country: '',
            pincode: '',
          },
          noofWorkers: 5,
          noOfSubdivisions: 5,
          noOfChurches: 5,
          coordinator: {
            _id: '1',
            firstName: 'athira',
            lastName: 'athira',
            dob: moment('12-11-2000'),
            doj: moment('12-11-2000'),
            designation: {
              _id: '1',
              name: 'TL',
              createdAt: moment(),
              updatedAt: moment(),
            },
            department: {
              _id: '1',
              name: 'IT',
              createdAt: moment(),
              updatedAt: moment(),
            },
            age: 25,
            gender: 'Female',
            phone: '123476798',
            email: 'test@gmail.com',
            formattedId: 'test',
            createdAt: moment(),
            updatedAt: moment(),
          },
          seniorLeader: {
            _id: '1',
            firstName: 'athira',
            lastName: 'athira',
            dob: moment('12-11-2000'),
            doj: moment('12-11-2000'),
            designation: {
              _id: '1',
              name: 'TL',
              createdAt: moment(),
              updatedAt: moment(),
            },
            department: {
              _id: '1',
              name: 'IT',
              createdAt: moment(),
              updatedAt: moment(),
            },
            age: 25,
            gender: 'Female',
            phone: '123476798',
            email: 'test@gmail.com',
            formattedId: 'test',
            createdAt: moment(),
            updatedAt: moment(),
          },
          juniorLeader: {
            _id: '1',
            firstName: 'athira',
            lastName: 'athira',
            dob: moment('12-11-2000'),
            doj: moment('12-11-2000'),
            designation: {
              _id: '1',
              name: 'TL',
              createdAt: moment(),
              updatedAt: moment(),
            },
            department: {
              _id: '1',
              name: 'IT',
              createdAt: moment(),
              updatedAt: moment(),
            },
            age: 25,
            gender: 'Female',
            phone: '123476798',
            email: 'test@gmail.com',
            formattedId: 'test',
            createdAt: moment(),
            updatedAt: moment(),
          }, createdAt: moment(),
          updatedAt: moment(),
        },
        subDivision: {
          _id: '1',
          subDivisionName: 'subdivision 1',

        },
        mainCategory: 'Fr request',
        sanction: '50000',
        requestAmount: 0,
        lastUpdateDate: moment(),
        releaseAmount: 0,
        transferredAmount: 0,
        transferredDate: moment(),
        transferredBank: {
          bankname: 'Canara',
          branchname: 'Thodupuzha',
          accountNumber: '4567799',
          IFSCCode: '222',
          beneficiary: '22',

        },
        modeOfPayment: '',
        transactionNumber: '' },
      {
        _id: '2',
        IROno: '1235',
        IROdate: moment(),
        division: {
          divisionName: 'Division 1',
          _id: '1',
          divisionId: '233',
          contactNumber: '89000333',
          email: 'division@gmail.com',
          address: {
            buildingName: '',
            street: '',
            city: '',
            district: '',
            state: '',
            country: '',
            pincode: '',
          },
          noofWorkers: 5,
          noOfSubdivisions: 5,
          noOfChurches: 5,
          coordinator: {
            _id: '1',
            firstName: 'athira',
            lastName: 'athira',
            dob: moment('12-11-2000'),
            doj: moment('12-11-2000'),
            designation: {
              _id: '1',
              name: 'TL',
              createdAt: moment(),
              updatedAt: moment(),
            },
            department: {
              _id: '1',
              name: 'IT',
              createdAt: moment(),
              updatedAt: moment(),
            },
            age: 25,
            gender: 'Female',
            phone: '123476798',
            email: 'test@gmail.com',
            formattedId: 'test',
            createdAt: moment(),
            updatedAt: moment(),
          },
          seniorLeader: {
            _id: '1',
            firstName: 'athira',
            lastName: 'athira',
            dob: moment('12-11-2000'),
            doj: moment('12-11-2000'),
            designation: {
              _id: '1',
              name: 'TL',
              createdAt: moment(),
              updatedAt: moment(),
            },
            department: {
              _id: '1',
              name: 'IT',
              createdAt: moment(),
              updatedAt: moment(),
            },
            age: 25,
            gender: 'Female',
            phone: '123476798',
            email: 'test@gmail.com',
            formattedId: 'test',
            createdAt: moment(),
            updatedAt: moment(),
          },
          juniorLeader: {
            _id: '1',
            firstName: 'athira',
            lastName: 'athira',
            dob: moment('12-11-2000'),
            doj: moment('12-11-2000'),
            designation: {
              _id: '1',
              name: 'TL',
              createdAt: moment(),
              updatedAt: moment(),
            },
            department: {
              _id: '1',
              name: 'IT',
              createdAt: moment(),
              updatedAt: moment(),
            },
            age: 25,
            gender: 'Female',
            phone: '123476798',
            email: 'test@gmail.com',
            formattedId: 'test',
            createdAt: moment(),
            updatedAt: moment(),
          }, createdAt: moment(),
          updatedAt: moment(),
        },
        subDivision: {
          _id: '1',
          subDivisionName: 'subdivision 1',
        },
        mainCategory: 'Fr request',
        sanction: '50000',
        requestAmount: 50000,
        lastUpdateDate: moment(),
        releaseAmount: 0,
        transferredAmount: 0,
        transferredDate: moment(),
        transferredBank: {
          bankname: 'Canara',
          branchname: 'Thodupuzha',
          accountNumber: '4567799',
          IFSCCode: '222',
          beneficiary: '22',

        },
        modeOfPayment: '',
        transactionNumber: '' },
      {
        _id: '2',
        IROno: '1235',
        IROdate: moment(),
        division: {
          divisionName: 'Division 1',
          _id: '1',
          divisionId: '233',
          contactNumber: '89000333',
          email: 'division@gmail.com',
          address: {
            buildingName: '',
            street: '',
            city: '',
            district: '',
            state: '',
            country: '',
            pincode: '',
          },
          noofWorkers: 5,
          noOfSubdivisions: 5,
          noOfChurches: 5,
          coordinator: {
            _id: '1',
            firstName: 'athira',
            lastName: 'athira',
            dob: moment('12-11-2000'),
            doj: moment('12-11-2000'),
            designation: {
              _id: '1',
              name: 'TL',
              createdAt: moment(),
              updatedAt: moment(),
            },
            department: {
              _id: '1',
              name: 'IT',
              createdAt: moment(),
              updatedAt: moment(),
            },
            age: 25,
            gender: 'Female',
            phone: '123476798',
            email: 'test@gmail.com',
            formattedId: 'test',
            createdAt: moment(),
            updatedAt: moment(),
          },
          seniorLeader: {
            _id: '1',
            firstName: 'athira',
            lastName: 'athira',
            dob: moment('12-11-2000'),
            doj: moment('12-11-2000'),
            designation: {
              _id: '1',
              name: 'TL',
              createdAt: moment(),
              updatedAt: moment(),
            },
            department: {
              _id: '1',
              name: 'IT',
              createdAt: moment(),
              updatedAt: moment(),
            },
            age: 25,
            gender: 'Female',
            phone: '123476798',
            email: 'test@gmail.com',
            formattedId: 'test',
            createdAt: moment(),
            updatedAt: moment(),
          },
          juniorLeader: {
            _id: '1',
            firstName: 'athira',
            lastName: 'athira',
            dob: moment('12-11-2000'),
            doj: moment('12-11-2000'),
            designation: {
              _id: '1',
              name: 'TL',
              createdAt: moment(),
              updatedAt: moment(),
            },
            department: {
              _id: '1',
              name: 'IT',
              createdAt: moment(),
              updatedAt: moment(),
            },
            age: 25,
            gender: 'Female',
            phone: '123476798',
            email: 'test@gmail.com',
            formattedId: 'test',
            createdAt: moment(),
            updatedAt: moment(),
          }, createdAt: moment(),
          updatedAt: moment(),
        },
        subDivision: {
          _id: '1',
          subDivisionName: 'subdivision 1',
        },
        mainCategory: 'Fr request',
        sanction: '50000',
        requestAmount: 50000,
        lastUpdateDate: moment(),
        releaseAmount: 0,
        transferredAmount: 0,
        transferredDate: moment(),
        transferredBank: {
          bankname: 'Canara',
          branchname: 'Thodupuzha',
          accountNumber: '4567799',
          IFSCCode: '222',
          beneficiary: '22',

        },
        modeOfPayment: '',
        transactionNumber: '' },

      ],
      // error: null,
      message: 'fetched data',
      result: 'success',
      timeout: 500,
    }),
  ),
  // eslint-disable-next-line @typescript-eslint/naming-convention
  saveRelease: (IROrelease: IROrder)=>getStandardResponse<number>(
    dummyRequest({
      data: IROrelease,
      // error: null,
      message: 'Network Error',
      result: 'success',
      timeout: 500,
    }),
  ),
};
