import moment from 'moment';
import { dummyRequest, getStandardResponse } from '../../../extras/CommonHelpers';
import axios from 'axios';

export default {
  getCount: () => getStandardResponse<number>(
    axios.get('/worker/count'),
  ),
  approveWorker: ( id:string) => getStandardResponse<number>(
    dummyRequest({
      data: id,
      // error: null,
      message: 'Approved',
      result: 'success',
      timeout: 500,
    }),
  ),
  getWorkerById: (workersId: string) => getStandardResponse<WorkersDetails>(
    dummyRequest<WorkersDetails>({
      data: {
        IETWorker: {
          _id: '',
          workerCode: '',
          firstName: '',
          lastName: '',
          missionaryOrNonMissionary: 'missionary',
          dob: moment(),
          gender: 'Female',
          age: 0,
          maritalStatus: 'Unmarried',
          highestQualification: '',
          motherToungue: 'Malayalam - മലയാളം',
          communicationLanguage: 'Malayalam - മലയാളം',
          languagesKnown: [],
          email: '',
          phone: '',
          alternativeMobileNumber: '',
          PANNo: 'string',
          aadhaar: { aadhaarFile: {
            _id: '',
            name: '',
            size: 0,
            type: 'image/png',
            storage: 'Drive',
            fileId: '',
            downloadURL: null,
            private: false,
            createdAt: moment(),
            updatedAt: moment(),
          }, aadhaarNo: '467389' },

          voterId: {
            voterIdFile: {
              _id: '',
              name: '',
              size: 0,
              type: 'image/png',
              storage: 'Drive',
              fileId: '',
              downloadURL: null,
              private: false,
              createdAt: moment(),
              updatedAt: moment(),
            }, voterIdNo: '467389' },
          licenseNumber: '',
          permanentAddress: {
            buildingName: '',
            streetAddress: '',
            city: '',
            district: '',
            state: '',
            country: '',
            pincode: '',
          },
          currentAddress: {
            buildingName: '',
            streetAddress: '',
            city: '',
            district: '',
            state: '',
            country: '',
            pincode: '',
          },
          createdAt: moment(),
          updatedAt: moment(),
        },
        officialDetails: { noOfYrsInOrg: 0,
          leftOrg: moment(),
          reasonToDeactivate: 'Voluntarily Left',
          remarks: 'Good',
          subDivision: {
            _id: '123',
            subDivisionName: 'division',
          },
          status: 'Left',
          joinedDivOn: moment(),
          leftDivOn: moment(),
          residingAddress: {
            buildingName: '',
            streetAddress: '',
            city: '',
            district: '',
            state: '',
            country: '',
            pincode: '',
          },
          noOfChurches: 0,
        },
        supportDetails: {
          currentDesignation: {
            _id: 'dsf',
            name: 'Co-ordinator',
            createdAt: moment(),
            updatedAt: moment(),
          },
          totalNoYearsInMinistry: 1,
          typeOfFamily: 'Single Missionary',
          typeofChurch: 'With Church',
          selfSupport: true,

        },
        supportStructure: {
          basicAllowance: 0,
          hraAllowance: 1,
          spouseAllowance: 0,
          positionalAllowance: 0,
          specialAllowance: 0,
          impactDeduction: 0,
          telAllowance: 0,
          pionMissionaryFund: 0,
          MUTDeduction: 0,
        },


      },
      // error: null,
      message: 'Approved',
      result: 'success',
      timeout: 500,
    }),
  ),
  getOfficialDetailsById: (workersId: string) => getStandardResponse<IETWorker>(
    dummyRequest({
      data: {
        _id: workersId,
        workerCode: '111',
        firstName: 'Athira',
        lastName: 'Haridas',
        missionaryOrNonMissionary: '',
        dob: moment(),
        gender: 'Female',
        age: '',
        maritalStatus: '',
        highestQualification: '',
        motherToungue: '',
        communicationLanguage: '',
        languagesKnown: '',
        email: 'athiraharidas@gmail.com',
        phone: '7592099483',
        alternativeMobileNumber: '',
        PANNo: '',
        aadhaarNumber: '',
        voterId: '',
        licenseNumber: '',
        permanentAddress: 'Kottappady(H)',
        permanentAddressCity: 'Thodupuzha',
        permanentAddressDistrict: 'Idukki',
        permanentAddressState: 'Kerala',
        permanentAddressCountry: 'India',
        permanentAddressPincode: '685581',
        currentAddress: 'Kottappady(H)',
        currentAddressCity: 'Thodupuzha',
        currentAddressDistrict: 'Idukki',
        currentAddressState: 'Kerala',
        currentAddressCountry: 'India',
        currentAddressPincode: '685581',
        spouse: '',
      },
      // error: null,
      message: 'Approved',
      result: 'success',
      timeout: 500,
    }),
  ),
  getSupportDetailsById: (workersId: string) => getStandardResponse<SupportDetails>(
    dummyRequest({
      data: {
        _id: workersId,
        currentDesignation: {
          name: 'Co-ordinator',
        },
        totalNoYearsInMinistry: 1,
        typeOfFamily: 'singleMissionary',
        typeofChurch: 'withChurch',
        selfSupport: 'yes' },
      // error: null,
      message: 'Approved',
      result: 'success',
      timeout: 500,
    }),
  ),
  getSupportStructureById: (workersId: string) => getStandardResponse<SupportStructure>(
    dummyRequest({
      data: {
        _id: workersId,
        basicAllowance: '100000',
        hraAllowance: 1,
        spouseAllowance: '10',
        positionalAllowance: '10',
        specialAllowance: 'yes',
        impactDeduction: '',
        telAllowance: '',
        pionMissionaryFund: '',
        MUTDeduction: '' },
      // error: null,
      message: 'Approved',
      result: 'success',
      timeout: 500,
    }),
  ),
  getBasicDetailsById: (workersId: string) => getStandardResponse<IETWorker>(
    dummyRequest({
      data: {
        _id: workersId,
        workerCode: '111',
        firstName: 'Athira',
        lastName: 'Haridas',
        missionaryOrNonMissionary: '',
        dob: moment(),
        gender: 'Female',
        age: '',
        maritalStatus: '',
        highestQualification: '',
        motherToungue: '',
        communicationLanguage: '',
        languagesKnown: '',
        email: 'athiraharidas@gmail.com',
        phone: '7592099483',
        alternativeMobileNumber: '',
        PANNo: '',
        aadhaarNumber: '',
        voterId: '',
        licenseNumber: '',
        permanentAddress: 'Kottappady(H)',
        permanentAddressCity: 'Thodupuzha',
        permanentAddressDistrict: 'Idukki',
        permanentAddressState: 'Kerala',
        permanentAddressCountry: 'India',
        permanentAddressPincode: '685581',
        currentAddress: 'Kottappady(H)',
        currentAddressCity: 'Thodupuzha',
        currentAddressDistrict: 'Idukki',
        currentAddressState: 'Kerala',
        currentAddressCountry: 'India',
        currentAddressPincode: '685581',
        spouse: '',
      },
      // error: null,
      message: 'Approved',
      result: 'success',
      timeout: 500,
    }),
  ),
  addWorker: (action: string ) => getStandardResponse<number>(
    dummyRequest({
      data: 1,
      // error: null,
      message: action+'ed staff',
      result: 'success',
      timeout: 500,
    }),
  ),
  getAll: () => getStandardResponse<[]>(
    dummyRequest({
      data: [{
        _id: 1,
        workerCode: '111',
        firstName: 'Athira',
        lastName: 'Haridas',
        missionaryOrNonMissionary: '',
        dob: moment(),
        gender: 'Female',
        age: '',
        maritalStatus: '',
        highestQualification: '',
        motherToungue: '',
        communicationLanguage: '',
        languagesKnown: '',
        email: '',
        phone: '',
        alternativeMobileNumber: '',
        PANNo: '',
        aadhaarNumber: '',
        voterId: '',
        licenseNumber: '',
        permanentAddress: '',
        permanentAddressCity: '',
        permanentAddressDistrict: '',
        permanentAddressState: '',
        permanentAddressCountry: '',
        permanentAddressPincode: '',
        currentAddress: '',
        currentAddressCity: '',
        currentAddressDistrict: '',
        currentAddressState: '',
        currentAddressCountry: '',
        currentAddressPincode: '',
        spouse: '' },
      {
        _id: 2,
        workerCode: '222',
        firstName: 'Sanjay',
        lastName: 'Sailas',
        missionaryOrNonMissionary: '',
        dob: moment(),
        gender: 'Male',
        age: '',
        maritalStatus: '',
        highestQualification: '',
        motherToungue: '',
        communicationLanguage: '',
        languagesKnown: '',
        email: '',
        phone: '',
        alternativeMobileNumber: '',
        PANNo: '',
        aadhaarNumber: '',
        voterId: '',
        licenseNumber: '',
        permanentAddress: '',
        permanentAddressCity: '',
        permanentAddressDistrict: '',
        permanentAddressState: '',
        permanentAddressCountry: '',
        permanentAddressPincode: '',
        currentAddress: '',
        currentAddressCity: '',
        currentAddressDistrict: '',
        currentAddressState: '',
        currentAddressCountry: '',
        currentAddressPincode: '',
        spouse: '' },
      ],
      // error: null,
      message: 'fetched data',
      result: 'success',
      timeout: 500,
    }),
  ),
  getDesignation: () => getStandardResponse<[]>(
    dummyRequest({
      data: [
        { name: 'Co-ordinator' },
        { name: 'Native Pastor' },
        { name: 'Evangelist' },
        { name: 'Associate Pastor' },
        { name: 'Ordained Pastor' },
        { name: 'Area Supervisor' },
        { name: 'Sub-Division Supervisor' },
        { name: 'Officiating Coordinator' },
        { name: 'Divisional Coordinator' },
        { name: 'Staff/Employees' },
        { name: 'Non-Missionary' },
      ],
      // error: null,
      message: 'Network Error',
      result: 'success',
      timeout: 500,
    }),
  ),
  markAsRemove: ( workerId: string) => getStandardResponse<number>(
    dummyRequest({
      data: workerId,
      // error: null,
      message: 'deleted',
      result: 'success',
      timeout: 500,
    }),
  ),
  getChild: () => getStandardResponse<[]>(
    dummyRequest({
      data: [
        {
          _id: '1',
          type: 'New',
          firstName: 'Neha',
          lastName: 'Thomas',
          dob: moment(),
          childSupport: 'Level 1',
          childOf: { _id: 1,
            workerCode: '111',
            firstName: 'Athira',
            lastName: 'Haridas',
            missionaryOrNonMissionary: '',
            dob: moment(),
            gender: 'Female',
            age: '',
            maritalStatus: '',
            highestQualification: '',
            motherToungue: '',
            communicationLanguage: '',
            languagesKnown: [],
            email: 'athiraharidas@gmail.com',
            phone: '7592099483',
            alternativeMobileNumber: '',
            PANnumber: '',
            aadhaarNumber: '',
            voterId: '',
            licenseNumber: '',
            permanentAddress: 'Kottappady(H)',
            permanentAddressCity: 'Thodupuzha',
            permanentAddressDistrict: 'Idukki',
            permanentAddressState: 'Kerala',
            permanentAddressCountry: 'India',
            permanentAddressPincode: '685581',
            currentAddress: 'Kottappady(H)',
            currentAddressCity: 'Thodupuzha',
            currentAddressDistrict: 'Idukki',
            currentAddressState: 'Kerala',
            currentAddressCountry: 'India',
            currentAddressPincode: '685581',
            spouseOfAnotherStaff: '' },
          studying: false,
          classOfStudy: '',
          working: false,
          occupation: '',
          qualification: '' },
      ],
      // error: null,
      message: 'Network Error',
      result: 'success',
      timeout: 500,
    }),
  ),
  addChild: (action: string ) => getStandardResponse<number>(
    dummyRequest({
      data: 1,
      // error: null,
      message: action+'ed Child',
      result: 'success',
      timeout: 500,
    }),
  ),
  getChildById: (childId: string) => getStandardResponse<CreatableChild>(
    dummyRequest<CreatableChild>({
      data: {
        type: 'New',
        firstName: 'Neha',
        lastName: 'Thomas',
        dob: moment(),
        childSupport: 'Level 1',
        childOf: { _id: '',
          workerCode: '',
          firstName: '',
          lastName: '',
          missionaryOrNonMissionary: 'missionary',
          dob: moment(),
          gender: 'Male',
          age: 0,
          maritalStatus: 'Unmarried',
          highestQualification: '',
          motherToungue: 'Malayalam - മലയാളം',
          communicationLanguage: 'Malayalam - മലയാളം',
          languagesKnown: [],
          email: '',
          phone: '',
          alternativeMobileNumber: '',
          PANNo: 'string',
          aadhaar: { aadhaarFile: {
            _id: '',
            name: '',
            size: 0,
            type: 'image/png',
            storage: 'Drive',
            fileId: '',
            downloadURL: null,
            private: false,
            createdAt: moment(),
            updatedAt: moment(),
          }, aadhaarNo: '467389' },

          voterId: { voterIdFile: {
            _id: '',
            name: '',
            size: 0,
            type: 'image/png',
            storage: 'Drive',
            fileId: '',
            downloadURL: null,
            private: false,
            createdAt: moment(),
            updatedAt: moment(),
          }, voterIdNo: '467389' },
          licenseNumber: '',
          permanentAddress: {
            buildingName: '',
            streetAddress: '',
            city: '',
            district: '',
            state: '',
            country: '',
            pincode: '',
          },
          currentAddress: {
            buildingName: '',
            streetAddress: '',
            city: '',
            district: '',
            state: '',
            country: '',
            pincode: '',
          },
          createdAt: moment(),
          updatedAt: moment(),
        },
        studying: true,
        classOfStudy: '',
        working: false,
        occupation: '',
        qualification: '',

      },
      // error: null,
      message: 'Approved',
      result: 'success',
      timeout: 500,
    }),
  ),
  editChild: (action: string ) => getStandardResponse<number>(
    dummyRequest({
      data: 1,
      // error: null,
      message: action+'ed Child',
      result: 'success',
      timeout: 500,
    }),
  ),
  getSpouse: () => getStandardResponse<Spouse[]>(
    dummyRequest<Spouse[]>({
      data: [
        {
          _id: '1',
          firstName: 'Neha',
          lastName: 'Thomas',
          dob: moment(),
          email: 'Mathew@gmail.com',
          mobileNo: '798865444',
          working: true,
          occupation: '',
          qualification: '',
          languagesKnown: [],
          spouseOf: { _id: ' 1',
            workerCode: '111',
            firstName: 'Athira',
            lastName: 'Haridas',
            missionaryOrNonMissionary: '',
            dob: moment(),
            gender: 'Female',
            age: 21,
            maritalStatus: 'Unmarried',
            highestQualification: '',
            motherToungue: 'Malayalam - മലയാളം',
            communicationLanguage: 'Malayalam - മലയാളം',
            languagesKnown: [],
            email: 'athiraharidas@gmail.com',
            phone: '7592099483',
            alternativeMobileNumber: '',
            PANNo: '',
            aadhaar: { aadhaarFile: {
              _id: '',
              name: '',
              size: 0,
              type: 'image/png',
              storage: 'Drive',
              fileId: '',
              downloadURL: null,
              private: false,
              createdAt: moment(),
              updatedAt: moment(),
            }, aadhaarNo: '467389' },

            voterId: { voterIdFile: {
              _id: '',
              name: '',
              size: 0,
              type: 'image/png',
              storage: 'Drive',
              fileId: '',
              downloadURL: null,
              private: false,
              createdAt: moment(),
              updatedAt: moment(),
            }, voterIdNo: '467389' },
            licenseNumber: 'string',
            permanentAddress: {
              buildingName: '',
              streetAddress: '',
              city: '',
              district: '',
              state: '',
              country: '',
              pincode: '',
            },
            currentAddress: {
              buildingName: '',
              streetAddress: '',
              city: '',
              district: '',
              state: '',
              country: '',
              pincode: '',
            },
            createdAt: moment(),
            updatedAt: moment(),
          },
          createdAt: moment(),
          updatedAt: moment(),
        },
      ],
      // error: null,
      message: 'Network Error',
      result: 'success',
      timeout: 500,
    }),
  ),
  addSpouse: (action: string ) => getStandardResponse<number>(
    dummyRequest({
      data: 1,
      // error: null,
      message: action+'ed Spouse',
      result: 'success',
      timeout: 500,
    }),
  ),
  editSpouse: (action: string ) => getStandardResponse<number>(
    dummyRequest({
      data: 1,
      // error: null,
      message: action+'ed Spouse',
      result: 'success',
      timeout: 500,
    }),
  ),

  getSpouseById: (spouseId: string) => getStandardResponse<CreatableSpouse>(
    dummyRequest<CreatableSpouse>({
      data: {
        firstName: 'Akash',
        lastName: 'M',
        dob: moment(),
        email: 'akash@gmail.com',
        mobileNo: '798865444',
        spouseOf: { _id: ' 1',
          workerCode: '111',
          firstName: 'Athira',
          lastName: 'Haridas',
          missionaryOrNonMissionary: '',
          dob: moment(),
          gender: 'Female',
          age: 21,
          maritalStatus: 'Unmarried',
          highestQualification: '',
          motherToungue: 'Afrikaans',
          communicationLanguage: 'Afrikaans',
          languagesKnown: [],
          email: 'athiraharidas@gmail.com',
          phone: '7592099483',
          alternativeMobileNumber: '',
          PANNo: '',
          aadhaar: { aadhaarFile: {
            _id: '',
            name: '',
            size: 0,
            type: 'image/png',
            storage: 'Drive',
            fileId: '',
            downloadURL: null,
            private: false,
            createdAt: moment(),
            updatedAt: moment(),
          }, aadhaarNo: '467389' },

          voterId: { voterIdFile: {
            _id: '',
            name: '',
            size: 0,
            type: 'image/png',
            storage: 'Drive',
            fileId: '',
            downloadURL: null,
            private: false,
            createdAt: moment(),
            updatedAt: moment(),
          }, voterIdNo: '467389' },
          licenseNumber: 'string',
          permanentAddress: {
            buildingName: '',
            streetAddress: '',
            city: '',
            district: '',
            state: '',
            country: '',
            pincode: '',
          },
          currentAddress: {
            buildingName: '',
            streetAddress: '',
            city: '',
            district: '',
            state: '',
            country: '',
            pincode: '',
          },
          createdAt: moment(),
          updatedAt: moment(),
        },
        occupation: 'Business',
        qualification: 'MBA',
        languagesKnown: [],
        working: true,
        createdAt: moment(),
        updatedAt: moment(),
      },
      // error: null,
      message: 'Network Error',
      result: 'success',
      timeout: 500,
    }),
  ),

};
