import moment from 'moment';
import { dummyRequest, getStandardResponse } from '../../../extras/CommonHelpers';

export default {
  getCount: () => {
    return getStandardResponse<number>(
      dummyRequest({
        data: 5,
        // error: null,
        message: 'Network Error',
        result: 'success',
        timeout: 500,
      }),
    );
  },
  approveWorker: ( id:string) => getStandardResponse<number>(
    dummyRequest({
      data: id,
      // error: null,
      message: 'Approved',
      result: 'success',
      timeout: 500,
    }),
  ),
  getWorkerById: (workersId: string) => getStandardResponse<WorkersDetails>(
    dummyRequest<WorkersDetails>({
      data: {
        basicDetails: { _id: workersId,
          workerCode: '111',
          firstName: 'Athira',
          secondName: 'Haridas',
          missionaryOrNonMissionary: '',
          dob: moment(),
          gender: 'Femaile',
          age: '',
          maritalStatus: '',
          highestQualification: '',
          motherToungue: '',
          communicationLanguage: '',
          languagesKnown: '',
          emailId: 'athiraharidas@gmail.com',
          mobileNumber: '7592099483',
          alternativeMobileNumber: '',
          PANnumber: '',
          aadhaarNumber: '',
          voterId: '',
          licenseNumber: '',
          permanentAddress: 'Kottappady(H)',
          permanentAddressCity: 'Thodupuzha',
          permanentAddressDistrict: 'Idukki',
          permanentAddressState: 'Kerala',
          permanentAddressCountry: 'India',
          permanentAddressPincode: '685581',
          currentAddress: 'Kottappady(H)',
          currentAddressCity: 'Thodupuzha',
          currentAddressDistrict: 'Idukki',
          currentAddressState: 'Kerala',
          currentAddressCountry: 'India',
          currentAddressPincode: '685581',
          spouseOfAnotherStaff: '' },
        officialDetails: { _id: '123',
          workerCode: '111',
          firstName: 'Athira',
          secondName: 'Haridas',
          missionaryOrNonMissionary: '',
          dob: moment(),
          gender: 'Femaile',
          age: '',
          maritalStatus: '',
          highestQualification: '',
          motherToungue: '',
          communicationLanguage: '',
          languagesKnown: '',
          emailId: 'athiraharidas@gmail.com',
          mobileNumber: '7592099483',
          alternativeMobileNumber: '',
          PANnumber: '',
          aadhaarNumber: '',
          voterId: '',
          licenseNumber: '',
          permanentAddress: 'Kottappady(H)',
          permanentAddressCity: 'Thodupuzha',
          permanentAddressDistrict: 'Idukki',
          permanentAddressState: 'Kerala',
          permanentAddressCountry: 'India',
          permanentAddressPincode: '685581',
          currentAddress: 'Kottappady(H)',
          currentAddressCity: 'Thodupuzha',
          currentAddressDistrict: 'Idukki',
          currentAddressState: 'Kerala',
          currentAddressCountry: 'India',
          currentAddressPincode: '685581',
          spouseOfAnotherStaff: '',
        },
        supportDetails: { _id: '',
          currentDesignation: {
            name: 'Co-ordinator',
          },
          totalNoYearsInMinistry: 1,
          typeOfFamily: 'Single Missionary',
          typeofChurch: 'With Church',
          selfSupport: 'Yes',

        },
        supportStructure: { _id: '',
          basicAllowance: '100000',
          hraAllowance: 1,
          spouseAllowance: '10',
          positionalAllowance: '10',
          specialAllowance: 'yes',
          impactDeduction: '',
          telAllowance: '',
          pionMissionaryFund: '',
          MUTDeduction: '',
        },
      },
      // error: null,
      message: 'Approved',
      result: 'success',
      timeout: 500,
    }),
  ),
  getOfficialDetailsById: (workersId: string) => getStandardResponse<OfficialDetails>(
    dummyRequest({
      data: {
        _id: workersId,
        workerCode: '111',
        firstName: 'Athira',
        secondName: 'Haridas',
        missionaryOrNonMissionary: '',
        dob: moment(),
        gender: 'Femaile',
        age: '',
        maritalStatus: '',
        highestQualification: '',
        motherToungue: '',
        communicationLanguage: '',
        languagesKnown: '',
        emailId: 'athiraharidas@gmail.com',
        mobileNumber: '7592099483',
        alternativeMobileNumber: '',
        PANnumber: '',
        aadhaarNumber: '',
        voterId: '',
        licenseNumber: '',
        permanentAddress: 'Kottappady(H)',
        permanentAddressCity: 'Thodupuzha',
        permanentAddressDistrict: 'Idukki',
        permanentAddressState: 'Kerala',
        permanentAddressCountry: 'India',
        permanentAddressPincode: '685581',
        currentAddress: 'Kottappady(H)',
        currentAddressCity: 'Thodupuzha',
        currentAddressDistrict: 'Idukki',
        currentAddressState: 'Kerala',
        currentAddressCountry: 'India',
        currentAddressPincode: '685581',
        spouseOfAnotherStaff: '',
      },
      // error: null,
      message: 'Approved',
      result: 'success',
      timeout: 500,
    }),
  ),
  getSupportDetailsById: (workersId: string) => getStandardResponse<SupportDetails>(
    dummyRequest({
      data: {
        _id: workersId,
        currentDesignation: {
          name: 'Co-ordinator',
        },
        totalNoYearsInMinistry: 1,
        typeOfFamily: 'singleMissionary',
        typeofChurch: 'withChurch',
        selfSupport: 'yes' },
      // error: null,
      message: 'Approved',
      result: 'success',
      timeout: 500,
    }),
  ),
  getSupportStructureById: (workersId: string) => getStandardResponse<SupportStructure>(
    dummyRequest({
      data: {
        _id: workersId,
        basicAllowance: '100000',
        hraAllowance: 1,
        spouseAllowance: '10',
        positionalAllowance: '10',
        specialAllowance: 'yes',
        impactDeduction: '',
        telAllowance: '',
        pionMissionaryFund: '',
        MUTDeduction: '' },
      // error: null,
      message: 'Approved',
      result: 'success',
      timeout: 500,
    }),
  ),
  getBasicDetailsById: (workersId: string) => getStandardResponse<BasicDetails>(
    dummyRequest({
      data: {
        _id: workersId,
        workerCode: '111',
        firstName: 'Athira',
        secondName: 'Haridas',
        missionaryOrNonMissionary: '',
        dob: moment(),
        gender: 'Femaile',
        age: '',
        maritalStatus: '',
        highestQualification: '',
        motherToungue: '',
        communicationLanguage: '',
        languagesKnown: '',
        emailId: 'athiraharidas@gmail.com',
        mobileNumber: '7592099483',
        alternativeMobileNumber: '',
        PANnumber: '',
        aadhaarNumber: '',
        voterId: '',
        licenseNumber: '',
        permanentAddress: 'Kottappady(H)',
        permanentAddressCity: 'Thodupuzha',
        permanentAddressDistrict: 'Idukki',
        permanentAddressState: 'Kerala',
        permanentAddressCountry: 'India',
        permanentAddressPincode: '685581',
        currentAddress: 'Kottappady(H)',
        currentAddressCity: 'Thodupuzha',
        currentAddressDistrict: 'Idukki',
        currentAddressState: 'Kerala',
        currentAddressCountry: 'India',
        currentAddressPincode: '685581',
        spouseOfAnotherStaff: '',
      },
      // error: null,
      message: 'Approved',
      result: 'success',
      timeout: 500,
    }),
  ),
  addWorker: (action: string ) => getStandardResponse<number>(
    dummyRequest({
      data: 1,
      // error: null,
      message: action+'ed staff',
      result: 'success',
      timeout: 500,
    }),
  ),
  getAll: () => getStandardResponse<[]>(
    dummyRequest({
      data: [{
        _id: 1,
        workerCode: '111',
        firstName: 'Athira',
        secondName: 'Haridas',
        missionaryOrNonMissionary: '',
        dob: moment(),
        gender: 'Femaile',
        age: '',
        maritalStatus: '',
        highestQualification: '',
        motherToungue: '',
        communicationLanguage: '',
        languagesKnown: '',
        emailId: '',
        mobileNumber: '',
        alternativeMobileNumber: '',
        PANnumber: '',
        aadhaarNumber: '',
        voterId: '',
        licenseNumber: '',
        permanentAddress: '',
        permanentAddressCity: '',
        permanentAddressDistrict: '',
        permanentAddressState: '',
        permanentAddressCountry: '',
        permanentAddressPincode: '',
        currentAddress: '',
        currentAddressCity: '',
        currentAddressDistrict: '',
        currentAddressState: '',
        currentAddressCountry: '',
        currentAddressPincode: '',
        spouseOfAnotherStaff: '' },
      {
        _id: 2,
        workerCode: '222',
        firstName: 'Sanjay',
        secondName: 'Sailas',
        missionaryOrNonMissionary: '',
        dob: moment(),
        gender: 'Male',
        age: '',
        maritalStatus: '',
        highestQualification: '',
        motherToungue: '',
        communicationLanguage: '',
        languagesKnown: '',
        emailId: '',
        mobileNumber: '',
        alternativeMobileNumber: '',
        PANnumber: '',
        aadhaarNumber: '',
        voterId: '',
        licenseNumber: '',
        permanentAddress: '',
        permanentAddressCity: '',
        permanentAddressDistrict: '',
        permanentAddressState: '',
        permanentAddressCountry: '',
        permanentAddressPincode: '',
        currentAddress: '',
        currentAddressCity: '',
        currentAddressDistrict: '',
        currentAddressState: '',
        currentAddressCountry: '',
        currentAddressPincode: '',
        spouseOfAnotherStaff: '' },
      ],
      // error: null,
      message: 'fetched data',
      result: 'success',
      timeout: 500,
    }),
  ),
  getDesignation: () => getStandardResponse<[]>(
    dummyRequest({
      data: [
        { name: 'Co-ordinator' },
        { name: 'Native Pastor' },
        { name: 'Evangelist' },
        { name: 'Associate Pastor' },
        { name: 'Ordained Pastor' },
        { name: 'Area Supervisor' },
        { name: 'Sub-Division Supervisor' },
        { name: 'Officiating Coordinator' },
        { name: 'Divisional Coordinator' },
        { name: 'Staff/Employees' },
        { name: 'Non-Missionary' },
      ],
      // error: null,
      message: 'Network Error',
      result: 'success',
      timeout: 500,
    }),
  ),
  markAsRemove: ( workerId: string) => getStandardResponse<number>(
    dummyRequest({
      data: workerId,
      // error: null,
      message: 'deleted',
      result: 'success',
      timeout: 500,
    }),
  ),
};
