import moment from 'moment';
import { dummyRequest, getStandardResponse } from '../../../extras/CommonHelpers';
import { categories, purposes } from './FRConfig';
import axios from 'axios';
export default {
  getCount: () => getStandardResponse<number>(
    axios.get('/fr/count'),
  ),
  getAll: () => getStandardResponse<Frrequest[]>(
    dummyRequest<Frrequest[]>({
      data: [{
        _id: '1',
        FRno: '1234',
        FRdate: moment('17-04-2023'),
        divisionName: 'test',
        subdivisionName: 'test',
        mainCategory: 'Fr request',
        requestAmount: '50000',
        lastUpdateDate: moment('17-04-2023'),
        sanction: 'Required' },
      {
        _id: '2',
        FRno: '1234',
        FRdate: moment('17-04-2023'),
        divisionName: 'test',
        subdivisionName: 'test',
        mainCategory: 'Fr request',
        requestAmount: '50000',
        lastUpdateDate: moment('17-04-2023'),
        sanction: 'Required' },
      {
        _id: '3',
        FRno: '1234',
        FRdate: moment('17-04-2023'),
        divisionName: 'test',
        subdivisionName: 'test',
        mainCategory: 'Fr request',
        requestAmount: '50000',
        lastUpdateDate: moment('17-04-2023'),
        sanction: 'Required' },
      {
        _id: '4',
        FRno: '1234',
        FRdate: moment('17-04-2023'),
        divisionName: 'test',
        subdivisionName: 'test',
        mainCategory: 'Fr request',
        requestAmount: '50000',
        lastUpdateDate: moment('17-04-2023'),
        sanction: 'Required' },

      ],
      // error: null,
      message: 'fetched data',
      result: 'success',
      timeout: 500,
    }),
  ),
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  getById: (fRId: string) => getStandardResponse<FR>(
    dummyRequest<FR>({
      data: {
        _id: '1',
        FRno: '1234',
        date: moment(),
        purpose: 'Worker',
        sanctionedAmount: 43,
        purposeWorker: {
          _id: 'efdsdsf',
          workerCode: 'string',
          firstName: 'string',
          lastName: 'string',
          missionaryOrNonMissionary: 'string',
          dob: moment(),
          gender: 'Male',
          age: 0,
          maritalStatus: 'Unmarried',
          highestQualification: 'string',
          motherToungue: 'string',
          communicationLanguage: 'string',
          languagesKnown: [],
          email: 'string',
          phone: 'string',
          alternativeMobileNumber: 'string',
          PANNo: 'string',
          aadhaar: { aadhaarFile: {
            _id: '',
            name: '',
            size: 0,
            type: 'image/png',
            storage: 'Drive',
            fileId: '',
            downloadURL: null,
            private: false,
            createdAt: moment(),
            updatedAt: moment(),
          }, aadhaarNo: '467389' },

          voterId: { voterIdFile: {
            _id: '',
            name: '',
            size: 0,
            type: 'image/png',
            storage: 'Drive',
            fileId: '',
            downloadURL: null,
            private: false,
            createdAt: moment(),
            updatedAt: moment(),
          }, voterIdNo: '467389' },
          licenseNumber: 'string',
          permanentAddress: {
            buildingName: '',
            streetAddress: '',
            city: '',
            district: '',
            state: '',
            country: '',
            pincode: '',
          },
          currentAddress: {
            buildingName: '',
            streetAddress: '',
            city: '',
            district: '',
            state: '',
            country: '',
            pincode: '',
          },
          createdAt: moment(),
          updatedAt: moment(),
        },
        createdAt: moment(),
        updatedAt: moment(),
      },
      // error: null,
      message: 'fetched data',
      result: 'success',
      timeout: 500,
    }),
  ),
  getPurposes: () => getStandardResponse<FRPurpose[]>(
    dummyRequest<FRPurpose[]>({
      data: purposes,
      // error: null,
      message: 'fetched data',
      result: 'success',
      timeout: 0,
    }),
  ),
  getMainCategory: () => getStandardResponse<MainCategory[]>(
    dummyRequest<MainCategory[]>({
      data: categories,
      // error: null,
      message: 'fetched data',
      result: 'success',
      timeout: 500,
    }),
  ),
  addParticulars: ( particularData: Particulars,
    action: 'add' | 'edit') => getStandardResponse<number>(
      dummyRequest({
        data: action,
        // error: null,
        message: action +'ed Particulars',
        result: 'success',
        timeout: 500,
      }),
    ),
  getParticulars: () => getStandardResponse<Particulars[]>(
    dummyRequest<Particulars[]>({
      data: [{
        _id: '1',
        mainCategory: 'main',
        subCategory1: 'sub',
        subCategory2: 'sub2',
        subCategory3: 'sub3',
        quantity: '12',
        month: 'January',
        requestedAmount: 300,
        narration: 'paticularss',
      },
      {
        _id: '2',
        mainCategory: 'main',
        subCategory1: 'sub',
        subCategory2: 'sub2',
        subCategory3: 'sub3',
        quantity: '12',
        month: 'January',
        requestedAmount: 300,
        narration: 'paticularss',
      },
      ],
      // error: null,
      message: 'fetched data',
      result: 'success',
      timeout: 500,
    }),
  ),
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  getAllRemarksById: (frId: string)=>getStandardResponse<Remark[]>(
    dummyRequest<Remark[]>({
      data: [
        {
          _id: '1',
          remark: 'HI Hlo',
          createdBy: { _id: '32490245',
            firstName: 'Jishnu',
            lastName: 'Raj',
            dob: moment(),
            doj: moment(),
            age: 25,
            gender: 'Female',
            phone: '',
            email: '',
            createdAt: moment(),
            updatedAt: moment(),
          },
          createdAt: moment(),
          updatedAt: moment(),
        },
        {
          _id: '2',
          // eslint-disable-next-line max-len
          remark: 'HI Hlo jhvaj hfgadkhjfga yukhj gfiuyakhfigfi  uaigqaufjuka jiuklfgfuaukg fgafiukf,adyuja yufafyuayiufgauiygfdiuagfukjgaukjfgaiufgiaugfiuagfiuagfk.afmlakaukgayjgfukhjagfjhafl,anhajhfukagfkuajh.kahfilahg lahifu aufg ukagfuiag uagfiuagfiu giuaguiaguiofuoauooiua or oua uoa uoa rouar iuoauoafuioa uaurua ua uoa yuar ur you8a ruak uoahyfuioafuiafuahyfuafhuafhuiaf',
          createdBy: { _id: '32490245',
            firstName: 'Jishnu',
            lastName: 'Raj',
            dob: moment(),
            doj: moment(),
            age: 25,
            gender: 'Female',
            phone: '',
            email: '',

            createdAt: moment(),
            updatedAt: moment(),
          },
          createdAt: moment(),
          updatedAt: moment(),
        },
        {
          _id: '3',
          remark: 'HI Hlo',
          createdBy: { _id: '32490245',
            firstName: 'Jishnu',
            lastName: 'Raj',
            dob: moment(),
            doj: moment(),
            age: 25,
            gender: 'Female',
            phone: '',
            email: '',
            createdAt: moment(),
            updatedAt: moment(),
          },
          createdAt: moment(),
          updatedAt: moment(),
        },
        {
          _id: '4',
          remark: 'HI Hlo',
          createdBy: { _id: '32490245',
            firstName: 'Jishnu',
            lastName: 'Raj',
            dob: moment(),
            doj: moment(),
            age: 25,
            phone: '123476798',
            email: 'test@gmail.com',
            gender: 'Female',
            createdAt: moment(),
            updatedAt: moment(),
          },
          createdAt: moment(),
          updatedAt: moment(),
        },
      ],
      message: 'fetched data',
      result: 'success',
      timeout: 0,
    }),
  ),
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  addRemarks: ( remark:CreatableRemark,
  ) => getStandardResponse<Remark>(
    dummyRequest({
      data: {
        _id: '1',
        remark: remark.remark,
        createdBy: { _id: '32490245',
          firstName: 'Jishnu',
          lastName: 'Raj',
          dob: moment(),
          doj: moment(),
          designation: {
            _id: 'jr20j0f',
            name: 'Tech Lead',
            createdAt: moment(),
            updatedAt: moment(),
          },
          department: {
            _id: '0tj30rftko',
            name: 'IT',
            createdAt: moment(),
            updatedAt: moment(),
          },
          phone: '',
          email: '',

          idFormat: '',
          createdAt: moment(),
          updatedAt: moment(),
        },
        createdAt: moment(),
        updatedAt: moment(),
      },
      // error: null,
      message: 'Remarks Updated',
      result: 'success',
      timeout: 500,
    }),
  ),


};
